middlewares/error-handler.js
建立middleware資料夾與error-handler.js檔案
route格式尚未決定, 
等確定需加上router.use掛載使用
=> 建立errorHandler

config/passport.js
=> 修改local登入回傳錯誤訊息

config/passport.js, package.json
將config/passport的req.currentUser變數刪除， middleware/auth/authenticated的req.user變數
調整 package.json start  新增 cross-env
=> 修正登入認証相關檔案 v2

config/passport.js, middleware/auth.js
刪除passport的local登入驗証，改由寫在本地路由上
=> 刪除 passport/loacl功能 v2

controllers/userController.js, routes/modules/user.js
=> 新增topUser功能

controllers/reply-controller.js, routes/modules/tweet.js
新增reply-controller
完成查看回覆功能
完成新增一筆回覆功能
=> 新增reply-controller

controllers/adminController.js, controllers/userController.js
=> modify: 調整登入路由json格式

controllers/userController.js
TypeError: Converting circular structure to JSON
/app/controllers/userController.js:74:13
先移除註冊回傳資料
=> 修正heroku錯誤移除註冊回傳資料

controllers/userController.js
=> 在取得追蹤資料中isFollowed

controllers/tweet-controller.js
修改/api/tweets/:tweet_id路由，不串連Reply表，並新增串連User、Like表格
新增檢查推文是否存在
調整回傳json的欄位，並新增likeCount、isLiked欄位
=>  修改getTweet關連資料表並調整回傳json欄位

controllers/userController.js
增加topUser User model where判斷式，增加排除account為 root及當前當入者
修改followings followers的json回傳欄位
=> 調整userController

controllers/adminController.js
改成 async awit寫法、推文相關Like/Reply相關資料
=> 新增刪除推文相關Like/Reply相關資料

controllers/userController.js, routes/modules/user.js
新增 api/users/currentUser 路由
取得當前使用者資訊
=> 新增取得當前使用者資訊路由

middleware/auth.js, routes/index.js
改使用_helpers.getUser 取代 req.user所取得的使用者資料，來驗証登入者是否是admin
=> 修改驗証管理者的取得user方式

controllers/adminController.js
=> 增加admin/getUsers 裡likedCount項目

controllers/followship-controller.js, models/followship.js, routes/index.js, routes/modules/followship.js
新增 新增/刪除追随者功能
調整followship的model檔案增加id為主鍵
=> 新增followship功能路由

controllers/adminController.js, routes/modules/admin.js
=> 新增admin路由getCurretUser

controllers/userController.js
=> 解決上傳單張圖片bug

controllers/tweet-controller.js
getTweet新增使用者帳號欄位
getTweets新增replyCount、llikeCount欄位
=> 調整tweet路由回傳json欄位

controllers/userController.js
=> 調整註冊路由成功訊息的位置

controllers/tweet-controller.js, controllers/userController.js
topUser新增account欄位
getTweets新增isLiked欄位
=> 調整回傳json欄位

app.js
因upload為上傳至本地端才需要，本專案只會上傳至imgur第三方伺服器，故刪除此程式
=> 刪除upload路徑

controllers/reply-controller.js, controllers/userController.js
修改取得使用者喜歡內容Get users/id/likes 路由:
新增likeCount/replyCount/isLiked
新增找不到user錯誤訊息
修改replyController
新增一則回覆回傳物件
=> userController / replyController 調整

controllers/tweet-controller.js
=> 檢查heroku head問題

controllers/followship-controller.js, controllers/tweet-controller.js, controllers/userController.js, middleware/auth.js
=> 修改回傳message文案

controllers/userController.js
=> 縮減userController json回傳欄位

config/passport.js
移除passport內 user 關聯資料庫 Tweet Reply 以及關聯資料庫 like 的include
=> 移除TweetReply關聯資料

controllers/followship-controller.js, controllers/reply-controller.js, controllers/tweet-controller.js
查詢時限制查詢出來的欄位
將檢查user的回傳 由throw new Error 改為 res.json
comment的內容不可空白判斷 加入.trim() 排除空白
=> 調整followship reply tweet的程式碼

controllers/userController.js
=> 增加json回傳user資料

controllers/followship-controller.js, controllers/userController.js
修改controllers user/followship使用者不存在的回傳方式
=> 修改使用者不存在的回傳方式
